### ISSUE TITLE
GenerateOwnPages doesn't work after upgrade to version v20.1

### ISSUE THREAD

**Issue by zuhry** [DevExpress-Examples/Reporting-Use-Subreport-To-Add-A-Chart#1]
Hi,

i faced a bug, after i upgrade the project from version 19 to 20.1 the subreport pages become portrait, while it should be landscape,
seems GenerateOwnPages= true configuration doesn't work now.
please help, thanks.

**Comment by e1em3ntoDX** [comment]
Hi Zuhry,

Thank you for reporting this issue.

I was able to reproduce this issue and I registered the following ticket in this regard: [T905992 - Report Merging - The page settings of a subreport are ignored when the GenerateOwnPages setting is enabled](https://supportcenter.devexpress.com/internal/ticket/details/t905992). I forwarded that ticket to our developers for further research. Add it to your favorites to be notified of our progress. 

Dmitry
